module.exports = {
	SHOULD_WIREFRAME_SATELLITE_MESH: true,
	DEFAULT_VIEW: "Wireframe",
	// DEFAULT_VIEW: "Satellite",
	ZOOM: 13,
	RADIUS: 5,
	DEFAULT_LOCATION_ORIGIN: [-42.8717, 147.3435],
	// DEFAULT_LOCATION_ORIGIN: [-42.878, 147.3525],
	DEFAULT_LOCATION_TITLE: 'Hobart',
	HEIGHT_MULTIPLIER: 5
}